title: Diego Carrasco # your name (or website title) here
logo: "/images/dacarras_2017_oval.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a full-time researcher at Centro de Medición MIDE UC, at Pontificia Universidad Católica de Chile. I hold a Doctoral degree in Psychology and a Master of Research in Psychological Methods from the University of Sussex. My work focuses on contextual effects research involving measurement and inferential problems for nested observations. This research line includes methodological challenges to national and international large-scale assessment, present in the exercise of school comparisons and learning environments research; I focus on substantive applications on civic education, teacher turnover, and judges voting behavior.  <br><br>
  You can reach me at dacarras.at.uc.cl 
  <br><br>
  <a href="https://www.linkedin.com/in/dacarras/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
